version: '3.9'

services:
  web:
    build: .
    container_name: api-gateway
    volumes:
      - ./backend:/app/backend
    working_dir: /app/backend
    command: ["gunicorn", "gateway.wsgi:application", "--bind", "0.0.0.0:8000"]
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.2
    container_name: keycloak
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8080:8080"

  db:
    image: postgres:15
    container_name: api-db
    environment:
      POSTGRES_DB: gateway
      POSTGRES_USER: gateway_user
      POSTGRES_PASSWORD: gateway_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:

